### ISSUE TITLE
Support GraalVM native compilation

### ISSUE THREAD

**Issue by begrossi** [chrisvest/stormpot#143]
I'm trying to compile stormpot jar with my application using GraalVM native-image compiler, and I'm getting only 2 errors, that looks simple to resolve.

```
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing stormpot.PaddedAtomicInteger.compareAndSet(BSlot.java:190)
Call path from entry point to stormpot.PaddedAtomicInteger.compareAndSet(int, int): 
        at stormpot.PaddedAtomicInteger.compareAndSet(BSlot.java:190)
        at stormpot.BSlot.live2dead(BSlot.java:98)
        at stormpot.BAllocThread.shutPoolDown(BAllocThread.java:242)
        at stormpot.BAllocThread.run(BAllocThread.java:90)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing stormpot.PaddedAtomicInteger.lazySet(BSlot.java:194)
Call path from entry point to stormpot.PaddedAtomicInteger.lazySet(int): 
        at stormpot.PaddedAtomicInteger.lazySet(BSlot.java:194)
        at stormpot.BSlot.dead2live(BSlot.java:82)
        at stormpot.BAllocThread.continuouslyReplenishPool(BAllocThread.java:105)
        at stormpot.BAllocThread.run(BAllocThread.java:89)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

It's solved using a `native-image.properties` file with an argument to initialize this class at compile time:
`Args = --initialize-at-build-time=stormpot.PaddedAtomicInteger`

But I think that maybe it's better to remove the using of `VarHandle` feature. Is it really necessary?

**Comment by chrisvest** [comment]
I don't know much about Graal myself, so I invite you to submit a PR. If Graal is going to be supported, there should also be a GitHub Actions PR build with it, to ensure it keeps working.

I'm still waiting for permission to work on this project myself, so it will be a while before I can commit or merge anything.

**Comment by chrisvest** [comment]
Sounds related: https://github.com/oracle/graal/issues/3028 – I wonder if Graal could fix this on their side.

**Comment by chrisvest** [comment]
PR got merged.
